add_newline = false

prompt_order = [
    "username",
    "directory",
    "nix_shell",
    "python",
    "git_branch",
    "git_state",
    "git_status",
    "cmd_duration",
    "jobs",
    "line_break",
    "character",
]

[git_status]
ahead = "↑"
behind = "↓"
diverged = "⤮ "
staged = "✮"
modified = " "
untracked = ""

[nix_shell]
impure_msg = " "
pure_msg = " "

[character]
symbol = "ﬦ"
use_symbol_for_status = true

[python]
symbol = " "
pyenv_prefix = ""