format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$env_var\
$aws\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$gcloud\
$crystal\
$cmd_duration\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

add_newline = false

[git_status]
style =	"bold bright-red"
ahead = "↑"
behind = "↓"
diverged = "⤮ "
staged = "✮"
modified = " "
untracked = ""

[nix_shell]
symbol = " "
style = "bold #0C81D6"
format = "via [$symbol]($style) "

[character]
success_symbol = "[](bold green) "
error_symbol = "[✗](bold red) "

[python]
symbol = " "
pyenv_prefix = ""

[aws]
format = "(as [$symbol$profile]($style) )"
style = "bold #0C81D6"
symbol = " "

[env_var]
variable = "DANGER_ZONE"
style = "bold #F38527"
symbol = "䀹DANGER"
format = "in [$symbol]($style) "

[dotnet]
disabled = true

[directory]
style =	"bold bright-red"